### PR TITLE
2.2.0 compatibility guide

### PR DESCRIPTION
**Pull request by daniCsorbaJB**
This update is to create the 2.2.0 compatibility guide. 
Related ticket is here: [KT-77014](https://youtrack.jetbrains.com/issue/KT-77014) [Docs] 2.2.0 Compatibility Guide

### CODE REVIEW

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 1]
```diff
@@ -0,0 +1,341 @@
...
+
+### Deprecate KotlinCompilationOutput#resourcesDirProvider
+
+> **Issue**: [KT-70620](https://youtrack.jetbrains.com/issue/KT-70620)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The `KotlinCompilationOutput#resourcesDirProvider` field is deprecated.
```
Comment (Tapchicoma) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Nit: `field` -> `property`?

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 2]
```diff
@@ -0,0 +1,341 @@
...
+
+### Change the type of annotationProcessorOptionProviders to use CommandLineArgumentProvider
+
+> **Issue**: [KT-58009](https://youtrack.jetbrains.com/issue/KT-58009)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The type of [`annotationProcessorOptionProviders`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-base-kapt/annotation-processor-option-providers.html#) in `BaseKapt` is changed from `MutableList<Any>`
```
Comment (Tapchicoma) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Not true - `BaseKapt.annotationProcessorOptionProviders` still has `MutableList<Any>` type and this property is deprecated.

Users should migrate to `BaseKapt.annotationProcessorOptionsProviders` (note: option**s**) which has `ListProperty<CommandLineArgumentProvider>` type.

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 3]
```diff
@@ -0,0 +1,341 @@
...
+>
+> **Short summary**: The `kotlin-android-extensions` plugin is deprecated. Use a separate plugin, `kotlin-parcelize`,
+> for the `Parcelable` implementation generator and the Android Jetpack's [view bindings](https://developer.android.com/topic/libraries/view-binding)
+> for synthetic views instead.
+>
+> **Deprecation cycle**:
+>
+> - 1.4.20: the plugin is deprecated
+> - 2.1.20: a configuration error is introduced, and no plugin code is executed
+> - 2.2.20: the plugin is removed
```
Comment (Tapchicoma) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: the plugin is removed
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md (hunk 2 above)
Comment (daniCsorbaJB) [reply docs/topics/compatibility-guides/compatibility-guide-22.md]: I see 👍  - thank you 

I restructured the entire section. What do you think of this version? 🤔 : 

### Deprecate BaseKapt.annotationProcessorOptionProviders

> **Issue**: [KT-58009](https://youtrack.jetbrains.com/issue/KT-58009)
>
> **Component**: Gradle
>
> **Incompatible change type**: source
>
> **Short summary**: The [`BaseKapt.annotationProcessorOptionProviders`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-base-kapt/annotation-processor-option-providers.html#) property is deprecated in favor of 
> `BaseKapt.annotationProcessorOptionsProviders`, which accepts a `MutableList<CommandLineArgumentProvider>` instead of a `MutableList<Any>`.
> This clearly defines the expected element type and prevents runtime failures caused by adding incorrect elements, such as nested lists.
> If your current code adds a list as a single element, replace the `add()` function with the `addAll()` function.
>
> **Deprecation cycle**:
>
> - 2.2.0: enforce new type in the API

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 4]
```diff
@@ -0,0 +1,341 @@
...
+### Deprecate BaseKapt.annotationProcessorOptionProviders
+
+> **Issue**: [KT-58009](https://youtrack.jetbrains.com/issue/KT-58009)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The [`BaseKapt.annotationProcessorOptionProviders`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-base-kapt/annotation-processor-option-providers.html#) property is deprecated in favor of 
+> `BaseKapt.annotationProcessorOptionsProviders`, which accepts a `MutableList<CommandLineArgumentProvider>` instead of a `MutableList<Any>`.
```
Comment (Tapchicoma) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> `BaseKapt.annotationProcessorOptionsProviders`, which accepts a `ListProperty<CommandLineArgumentProvider>` instead of a `MutableList<Any>`.
```

**Review by Tapchicoma — APPROVED** [review]

**Review by ilya-g — APPROVED** [review]

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 5]
```diff
@@ -339,3 +339,23 @@ perspective
...
+
+> **Issues**: [KT-71685](https://youtrack.jetbrains.com/issue/KT-71685), [KT-75632](https://youtrack.jetbrains.com/issue/KT-75632/), [KT-76196](https://youtrack.jetbrains.com/issue/KT-76196/).
+>
+> **Component**: Scripting
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: Kotlin 2.2.0 deprecates support for:
+>   * REPL: To continue to use REPL via `kotlinc`, opt in with the `-Xrepl` compiler option.
+>   * JSR-223: Since the [JSR](https://jcp.org/en/jsr/detail?id=223) is in **Withdrawn** state. The JSR-223 implementation continues to work with language version 1.9 but won't be migrated to use the K2 compiler in the future.
```
Comment (ligee) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: I'd prefer to say that we do not have plans to migrate it to the K2. This way we may have a way to reconsider.

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 6]
```diff
@@ -0,0 +1,574 @@
...
+
+### Prohibit constructor call and inheritance on type aliases with variance in expanded types in K2
+
+> **Issue**: [KTLC-4](https://youtrack.jetbrains.com/issue/KTLC-4)
+>
+> **Component**: Core language
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: Constructor calls and inheritance using type aliases that expand to types that use variance modifiers such as `out` are no longer allowed in K2.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> **Short summary**: Constructor calls and inheritance using type aliases that expand to types that use variance modifiers such as `out` are no longer supported by the K2 compiler.
```
"In K2" seems vague so I tried to add additional explanation. It's OK to use in the header though.

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 7]
```diff
@@ -0,0 +1,574 @@
...
+> **Incompatible change type**: binary
+>
+> **Short summary**: Functions declared in interfaces are now compiled to JVM default methods unless configured otherwise.
+> This may result in compilation errors in Java code when unrelated supertypes define conflicting implementations.
+> The behavior is controlled by the stable `-jvm-default` compiler option, which replaces the now deprecated `-Xjvm-default` option.
+> To restore the previous behavior, where default implementations are generated only in `DefaultImpls` classes and subclasses, use `-jvm-default=disable`.
+>
+> **Deprecation cycle**:
+>
+> - 2.2.0: `-jvm-default` compiler option is set to `enable` by default
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md:91]: Is the `-Xjvm-default- option deprecated at the same time?
And is the `-jvm-default` option documented in https://kotlinlang.org/docs/compiler-reference.html as part of another PR for Kotlin 2.2.0?

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 8]
```diff
@@ -0,0 +1,574 @@
...
+> **Component**: Core language
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: Functions and properties can no longer use a type parameter bound that has more restrictive visibility than the declaration itself.
+> This prevents exposing inaccessible types indirectly, which previously compiled without errors but led to runtime failures or IR validation errors in some cases.
+>
+> **Deprecation cycle**:
+>
+> - 2.1.0: report a warning when a type parameter has a bound that is not visible from the declaration’s visibility scope
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.1.0: report a warning when a type parameter has a bound that is not visible from the declaration's visibility scope
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 9]
```diff
@@ -0,0 +1,574 @@
...
+
+### Deprecate `AbstractDoubleTimeSource`
+
+> **Issue**: [KT-72137](https://youtrack.jetbrains.com/issue/KT-72137)
+>
+> **Component**: kotlin-stdlib
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: `AbstractDoubleTimeSource` is deprecated; use `AbstractLongTimeSource` instead.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Can you add a standard library API reference link for the preferred source? https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.time/-abstract-long-time-source/

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 10]
```diff
@@ -0,0 +1,574 @@
...
+
+### Deprecate `kotlin.native.Throws`
+
+> **Issue**: [KT-72137](https://youtrack.jetbrains.com/issue/KT-72137)
+>
+> **Component**: Kotlin/Native
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: `kotlin.native.Throws` is deprecated; use the common `kotlin.Throws` annotation instead.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Can you add a standard library API reference link for the preferred annoatation?
https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/-throws/

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 11]
```diff
@@ -0,0 +1,574 @@
...
+
+### Correct `setSource()` function in `KotlinCompileTool` to replace sources
+
+> **Issue**: [KT-59632](https://youtrack.jetbrains.com/issue/KT-59632)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: behavioral
+>
+> **Short summary**: The [`setSource()`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-kotlin-compile-tool/set-source.html#) function in [`KotlinCompileTool`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-kotlin-compile-tool/#) now replaces configured sources instead of adding to them.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> **Short summary**: The [`setSource()`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-kotlin-compile-tool/set-source.html#) function in the [`KotlinCompileTool`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-kotlin-compile-tool/#) interface now replaces configured sources instead of adding to them.
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 12]
```diff
@@ -0,0 +1,574 @@
...
+> If you want to add sources without replacing existing ones, use the [`source()`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-kotlin-compile-tool/source.html#) function.
+>
+> **Deprecation cycle**:
+>
+> - 2.2.0: enable new behavior
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: enable the new behavior
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 13]
```diff
@@ -0,0 +1,574 @@
...
+### Deprecate `KotlinCompilationOutput#resourcesDirProvider` property
+
+> **Issue**: [KT-70620](https://youtrack.jetbrains.com/issue/KT-70620)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The `KotlinCompilationOutput#resourcesDirProvider` property is deprecated.
+> Use `KotlinSourceSet.resources` in your Gradle build script instead to add additional resource directories.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Add link https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.plugin/-kotlin-source-set/resources.html

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 14]
```diff
@@ -0,0 +1,574 @@
...
+> **Incompatible change type**: source
+>
+> **Short summary**: The [`BaseKapt.annotationProcessorOptionProviders`](https://kotlinlang.org/api/kotlin-gradle-plugin/kotlin-gradle-plugin-api/org.jetbrains.kotlin.gradle.tasks/-base-kapt/annotation-processor-option-providers.html#) property is deprecated in favor of 
+> `BaseKapt.annotationProcessorOptionsProviders`, which accepts a `ListProperty<CommandLineArgumentProvider>` instead of a `MutableList<Any>`.
+> This clearly defines the expected element type and prevents runtime failures caused by adding incorrect elements, such as nested lists.
+> If your current code adds a list as a single element, replace the `add()` function with the `addAll()` function.
+>
+> **Deprecation cycle**:
+>
+> - 2.2.0: enforce new type in the API
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: enforce the new type in the API
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 15]
```diff
@@ -0,0 +1,574 @@
...
+>
+> **Short summary**: The `kotlin-android-extensions` plugin is deprecated. Use a separate plugin, `kotlin-parcelize`,
+> for the `Parcelable` implementation generator and the Android Jetpack's [view bindings](https://developer.android.com/topic/libraries/view-binding)
+> for synthetic views instead.
+>
+> **Deprecation cycle**:
+>
+> - 1.4.20: the plugin is deprecated
+> - 2.1.20: a configuration error is introduced, and no plugin code is executed
+> - 2.2.0: the plugin is removed
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Does this mean support for the plugin is removed in Kotlin?

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 16]
```diff
@@ -0,0 +1,574 @@
...
+
+### Deprecate `kotlin-android-extensions` plugin
+
+> **Issue**: [KT-72341](https://youtrack.jetbrains.com/issue/KT-72341/)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The `kotlin-android-extensions` plugin is deprecated. Use a separate plugin, `kotlin-parcelize`,
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: Add link to the parcelize plugin? https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.parcelize

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 17]
```diff
@@ -0,0 +1,574 @@
...
+> **Issue**: [KT-54110](https://youtrack.jetbrains.com/issue/KT-54110)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The ability to configure compiler options through the `kotlinOptions` DSL and the related
+> `KotlinCompile<KotlinOptions>` task interface is deprecated in favor of the new `compilerOptions` DSL.
+> As part of this deprecation, all properties in the `kotlinOptions` interface are now also individually marked as deprecated.
+> To migrate, use the `compilerOptions` DSL to configure compiler options.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> To migrate, use the `compilerOptions` DSL to configure compiler options. For guidance on the migration, see [Migrate from `kotlinOptions {}` to `compilerOptions {}`](gradle-compiler-options.md#migrate-from-kotlinoptions-to-compileroptions).
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 18]
```diff
@@ -0,0 +1,574 @@
...
+>
+> 2. Clear the commonization cache in the `~/.konan/*/klib/commonized` directory or run the following command: 
+>
+>    ```bash
+>    ./gradlew cleanNativeDistributionCommonization
+>    ```
+>
+> **Deprecation cycle**:
+>
+> - 2.2.0: commonization parameters are deprecated with an error
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: derprecate commonization parameters with an error
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 19]
```diff
@@ -0,0 +1,574 @@
...
+> **Short summary**: Options that were used to set up hierarchical structure and create intermediate source sets
+> between the common and intermediate source sets became obsolete.
+> The following compiler options are removed:
+> 
+> * `isCompatibilityMetadataVariantEnabled`
+> * `withGranularMetadata`
+> * `isKotlinGranularMetadataEnabled`
+>
+> **Deprecation cycle**:
+
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
>
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 20]
```diff
@@ -0,0 +1,574 @@
...
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The access to `KotlinCompilation.source` that allowed adding Kotlin source sets directly to the Kotlin
+> compilation has been deprecated.
+>
+> **Deprecation cycle**:
+>
+> - 1.9.0: report a warning when `KotlinComplation.source` is used
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 1.9.0: report a warning when `KotlinCompilation.source` is used
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 21]
```diff
@@ -0,0 +1,574 @@
...
+> - 1.9.20: raise this warning to an error
+> - 2.2.0: remove `KotlinComplation.source` from the Kotlin Gradle plugin; attempts to use it lead to "unresolved reference"
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: remove `KotlinCompilation.source` from the Kotlin Gradle plugin; attempts to use it lead to "unresolved reference"
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 22]
```diff
@@ -0,0 +1,574 @@
...
+
+### Deprecate `KotlinCompilation.source`
+
+> **Issue**: [KT-64991](https://youtrack.jetbrains.com/issue/KT-64991)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The access to `KotlinCompilation.source` that allowed adding Kotlin source sets directly to the Kotlin
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]: @danil-pavlov do you mean that the `source()` function is deprecated? It's  not clear what "the access" means for me 🤔

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 23]
```diff
@@ -0,0 +1,574 @@
...
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The `konanVersion` property in the `CInteropProcess` task is deprecated.
+> Use `CInteropProcess.kotlinNativeVersion` instead.
+>
+> **Deprecation cycle**:
+>
+> - 2.1.0: report a warning when `konanVersion` is used
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.1.0: report a warning when the `konanVersion` property is used
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 24]
```diff
@@ -0,0 +1,574 @@
...
+> - 2.2.0: raise this warning to an error
+> - 2.3.0: remove `konanVersion` property from the Kotlin Gradle plugin
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.3.0: remove the `konanVersion` property from the Kotlin Gradle plugin
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 25]
```diff
@@ -0,0 +1,574 @@
...
+### Deprecate `destinationDir` in `CInteropProcess`
+
+> **Issue**: [KT-71068](https://youtrack.jetbrains.com/issue/KT-71068)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The `destinationDir` property in the `CInteropProcess` task is deprecated.
+> Use `CInteropProcess.destinationDirectory.set()` instead.
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> Use the `CInteropProcess.destinationDirectory.set()` function instead.
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 26]
```diff
@@ -0,0 +1,574 @@
...
+>
+> **Deprecation cycle**:
+>
+> - 2.1.0: report a warning when `destinationDir` is used
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.1.0: report a warning when the `destinationDir` property is used
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 27]
```diff
@@ -0,0 +1,574 @@
...
+> - 2.2.0: raise this warning to an error
+> - 2.3.0: remove `destinationDir` from the Kotlin Gradle plugin
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.3.0: remove the `destinationDir` property from the Kotlin Gradle plugin
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 28]
```diff
@@ -0,0 +1,574 @@
...
+
+> **Issue**: [KT-74953](https://youtrack.jetbrains.com/issue/KT-74953)
+>
+> **Component**: Gradle
+>
+> **Incompatible change type**: source
+>
+> **Short summary**: The experimental `kotlinArtifacts` API is deprecated. Use the current DSL available in the Kotlin Gradle
+> plugin to [build final native binaries](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-build-native-binaries.html).
+> If it's not sufficient for migration, leave a comment in [this YT issue](https://youtrack.jetbrains.com/issue/KT-74953).
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md:568]: @danil-pavlov by "it" do you mean the current DSL?

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 29]
```diff
@@ -0,0 +1,574 @@
...
+>
+> **Deprecation cycle**:
+>
+> - 2.2.0: report a warning when `kotlinArtifacts` is used
```
Comment (sarahhaggarty) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: report a warning when the `kotlinArtifacts` API is used
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md (hunk 28 above)
Comment (danil-pavlov) [reply docs/topics/compatibility-guides/compatibility-guide-22.md:568]: yes, correct

File: docs/topics/compatibility-guides/compatibility-guide-22.md (hunk 22 above)
Comment (danil-pavlov) [reply docs/topics/compatibility-guides/compatibility-guide-22.md]: This is actually a deprecation cycle update of [this change](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-compatibility-guide.html#deprecated-api-for-adding-kotlin-source-sets-directly-to-the-kotlin-compilation), so I tried to be consistent with that text
Let's call it `KotlinCompilation.source` API? to be more general

File: docs/topics/compatibility-guides/compatibility-guide-22.md (hunk 15 above)
Comment (danil-pavlov) [reply docs/topics/compatibility-guides/compatibility-guide-22.md]: The plugin code is removed, see [KT-72341](https://youtrack.jetbrains.com/issue/KT-72341)

Comment (sarahhaggarty) [reply docs/topics/compatibility-guides/compatibility-guide-22.md]: OK, can you update to include "plugin code". I think that makes it much clearer :)

File: docs/topics/compatibility-guides/compatibility-guide-22.md [hunk 30]
```diff
@@ -0,0 +1,573 @@
...
+>
+> **Short summary**: The `kotlin-android-extensions` plugin is deprecated. Use a separate plugin, [`kotlin-parcelize`](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.parcelize),
+> for the `Parcelable` implementation generator and the Android Jetpack's [view bindings](https://developer.android.com/topic/libraries/view-binding)
+> for synthetic views instead.
+>
+> **Deprecation cycle**:
+>
+> - 1.4.20: the plugin is deprecated
+> - 2.1.20: a configuration error is introduced, and no plugin code is executed
+> - 2.2.0: the plugin is removed
```
Comment (danil-pavlov) [inline docs/topics/compatibility-guides/compatibility-guide-22.md]:
```suggestion
> - 2.2.0: the plugin code is removed
```

File: docs/topics/compatibility-guides/compatibility-guide-22.md (hunk 7 above)
Comment (daniCsorbaJB) [reply docs/topics/compatibility-guides/compatibility-guide-22.md:91]: Yes, it's deprecated at the same time
hmm 🤔 - it was introduced to the[ Gradle compiler options doc ](https://kotlinlang.org/docs/gradle-compiler-options.html)and not to the generic compiler-reference. Should it also be included there? 🤔

Comment (sarahhaggarty) [reply docs/topics/compatibility-guides/compatibility-guide-22.md:91]: Yes, it would be good to include it there too 👍
